### ISSUE TITLE
NASTOOL 群晖套件升级3.4.0后无法访问

### ISSUE THREAD

**Issue by AndyHuyidi** [hsuyelin/nas-tools#744]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.0

### 问题类型

主程序运行问题

### 问题描述

NASTOOL 群晖套件升级3.4.0后无法访问，试了很多次， 然后也请专业人员来看，还是解决不了。

<img width="936" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/48292864/24d01ea2-1cf6-447b-acae-18a9069fec3a">

**Comment by pplokijuhyg** [comment]
使用docker运行吧，我现在的配置
```
version: "3"
services:
  nas-tools:
    image: hsuyelin/nas-tools:latest
    ports:
      - 3000:3000        # 默认的webui控制端口
    volumes:
      - ./config:/config   # 冒号左边请修改为你想保存配置的路径
      - /volume2/movies:/volume2/movies   # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
    environment: 
      - PUID=0    # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0    # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=false  # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_CN_UPDATE=false # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
     #- REPO_URL=https://ghproxy.com/https://github.com/hsuyelin/nas-tools.git  # 当你访问github网络很差时，可以考虑解释本行注释
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
```
