### ISSUE TITLE
[错误报告]: Permission denied: 问题

### ISSUE THREAD

**Issue by 0nion1** [hsuyelin/nas-tools#822]
### 确认

- [x] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [x] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.1

### 问题类型

主程序运行问题

### 问题描述

我尝试docker拉取nas-tools，在配置媒体库的时候提示 《加载路径失败: [Errno 13] Permission denied: '/media'》，但是我同样权限拉取了一个jellyfin和qb就没问题。文件夹已经设置了owner

![Image](https://github.com/user-attachments/assets/a0bfa545-e8ec-4899-bd43-3799abff4578)

这是我的docker-compose
```
services:  
  nas-tools:  
    image: docker.1ms.run/hsuyelin/nas-tools:latest  
    container_name: nas-tools  
    ports:  
      - 3000:3000   
    volumes:  
      - /volume1/docker/nastools/config:/config  
      - /volume2/Downloads:/downloads
      - /volume2/Media:/media
    environment:   
      - PUID=1026  
      - PGID=100  
      - NASTOOL_AUTO_UPDATE=false  
      - NASTOOL_CN_UPDATE=false  
    restart: unless-stopped
```

### 发生问题时系统日志和配置文件

```bash

```
